# Generated by Django 4.2.30 on 2026-06-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_language', models.TextField()),
                ('generated_sql', models.TextField(blank=True)),
                ('result_data', models.JSONField(default=list)),
                ('chart_type', models.CharField(choices=[('bar', 'bar'), ('line', 'line'), ('table', 'table')], default='table', max_length=10)),
                ('insight', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
